# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: transcrypt
        # transcrypt installs its hook to pre-commit-crypt, copied to pre-commit.
        # "pre-commit install" will move it to pre-commit.legacy, which is special
        # cased in pre-commit ("Migration mode"). Here we run that hook explicitly
        # instead.
        name: transcrypt
        language: system
        entry: bash -c "bash $GIT_DIR/hooks/pre-commit-crypt"
      - id: yadm_ls_files_for_mutagen
        name: yadm_ls_files_for_mutagen
        language: system
        entry: just yadm_ls_files_for_mutagen
        always_run: true
        exclude: "."
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        # Exclude templated files
        exclude: '\#\#t'
      - id: check-added-large-files
