* Yadm Classes

- personal
- personal_ubuntu
- personal_mac
- remote + debian


* Transcrypt

We are using Transcrypt to encrypt some keys before checking in. Note that these
files are "##c.personal", so they only need to be encrypted on the "personal"
machine. For remote servers, use ssh forwarding instead.

See https://github.com/elasticdog/transcrypt.

Install with ~brew install transcrypt~

#+begin_src shell
## on local machine (where transcrypt is already configured)
yadm transcrypt --display

## or
yadm transcrypt -c aes-256-cbc -p '<Get password from bitwarden>'

## to see encrypted files
yadm transcrypt --list

## Flush credentials (may need --force)
yadm transcrypt -f
#+end_src

** .gitattributes

Configures which files are encrypted

#+begin_src shell :tangle ~/.gitattributes
.ssh/id_rsa.pub\#\#c.personal filter=crypt diff=crypt merge=crypt
.ssh/id_rsa\#\#c.personal filter=crypt diff=crypt merge=crypt
.ssh/id_ed25519.pub\#\#c.personal filter=crypt diff=crypt merge=crypt
.ssh/id_ed25519\#\#c.personal filter=crypt diff=crypt merge=crypt
.config/TabNine/registration_key filter=crypt diff=crypt merge=crypt
.config/rclone/rclone.conf filter=crypt diff=crypt merge=crypt
#+end_src


* zsh secrets

Make ~~/.zsh_secrets~ if you need any secrets that aren't committed. It is sourced via ~secrets.zsh~


* Alt files

We use alt files to

1. change the file wholesale (eg. Brewfile)
2. template the file to have slightly different content (eg. zshrc)

Some files are only useful on a specific class, but we don't bother removing
these or hiding them. They are addressed at point of use - ie. if it is a
zshcustom file, we might use templates to include them correctly in zshrc.


* Kinesis Advantage :ATTACH:
:PROPERTIES:
:ID:       84969743-6640-4c9d-bc73-5fab6ddc939d
:END:

https://kinesis-ergo.com/wp-content/uploads/kb500-qsg.pdf

- ~=m~ to switch to mac mode
- ~Program+\~ to switch off clicks
- Remapping: ~Prgrm+F12~ to start. Hit source, then destination to copy from source to destination
  + *Swap* ctrl and capslock
  + Copy alt to left shift
  + Copy win to key below X

- set repeat rate to 10cps Program-F9-F5

** Extra info

#+begin_example
Progrm-Ctrl-F10   Reset keyboard memory

Progrm-Backslash  Toggle keyclick mode
Progrm-Hyphen     Toggle tones for caps lock, etc.
Progrm-F9-xx      Change repeat rate to xx
                    F1 .5 cps  F2  3 cps F3  5 cps  F4   7 cps  F5   10 cps  F6   15 cps
                    F7 20 cps  F8 30 cps F9 40 cps  F10 60 cps  F11 125 cps  F12 300 cps

Progrm-Ctrl-F5    Toggle Dvorak/Qwerty mode

Progrm-Shift-F6   Toggle shift as sticky modifier
Progrm-Ctrl-F6    Toggle control as sticky modifier
Progrm-Alt-F6     Toggle alt as sticky modifier

Progrm-F12        Enter/exit remapping mode

Progrm-F11        Enter/exit macro definition mode
Progrm-F7         Make macro pause for data / End entering macro data
Progrm-F8         Put a half-second delay into a macro
Progrm-F10        Disable/Enable all macros

Shift-Shift-F12   Report firmware version (press both shift keys)
#+end_example

** Multimedia keys :ATTACH:

https://superuser.com/a/403765 & https://superuser.com/a/557689

~=n~ to turn on all multimedia keys

=F3 to toggle state of just F3


* Mac OS X setup notes

- yadm classes: personal, personal_mac (so that we can also do personal_ubuntu)
- maccy for clipboard editor
- paperwm.spoon, hammerspoon -> needs some manual settings changes
- iterm2 + config
- mouse speed, keyboard repeat rate
- nerd fonts via brew cask (iosevka) -> should be in Brewfile
- emacs-plus -> should be in Brewfile (but not options --with-dragon-icon --with-native-comp)
- vscode settings config (sync against stable!)
- lots of prompt stuff in prezto unnecessary - we're using starship
- atuin login + import
- yadm bootstrap
