# WARNING: Do not edit this file.
# It was generated by processing {{ yadm.source }}

source $(brew --prefix antigen)/share/antigen/antigen.zsh

# https://github.com/zsh-users/antigen/wiki/Cookbook#init-command
antigen init ~/.antigenrc
