# WARNING: Do not edit this file.
# It was generated by processing {{ yadm.source }}

# ------------ #
# Set up agent #
# ------------ #

{% if yadm.class == "personal" %}

# On graphical Ubuntu, gnome-keyring-daemon is running but doesn't set the right
# SSH_AUTH_SOCK variable
# https://warlord0blog.wordpress.com/2020/01/29/gnome-keyring-and-ssh-agent/

export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh

{% else %}

# On other OSes, we will start it in a reusable way:
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
    echo "'ssh-agent' has not been started since the last reboot. Starting 'ssh-agent' now."
    eval "$(ssh-agent -s)"
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock

{% endif %}

# -------- #
# Add keys #
# -------- #

{% if yadm.os == "Darwin" %}
# On OSX, id_rsa ssh key can be in keychain so it can be added with -K argument
ssh-add -l >/dev/null || ssh-add -K
{% else %}
ssh-add -l >/dev/null || ssh-add
{% endif %}
