# WARNING: Do not edit this file.
# It was generated by processing {{ yadm.source }}

{% if yadm.class == "personal_ubuntu" %}
# https://jamezrin.name/my-perfect-ssh-agent-configuration
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# # On graphical Ubuntu, gnome-keyring-daemon is running but doesn't set the right
# # SSH_AUTH_SOCK variable
# # https://warlord0blog.wordpress.com/2020/01/29/gnome-keyring-and-ssh-agent/
# export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh

ssh-add -l >/dev/null || ssh-add
{% endif %}

{% if yadm.class == "remote" %}
# No ssh-agent necessary: instead we use ForwardAgent to forward ssh-keys.
#
# This requires that
#
# - ssh-agent be running locally (echo $SSH_AUTH_SOCK)
# - no ssh-agent be running remotely
# - "ssh-add -l" shows keys locally
# - `ForwardAgent yes` in .ssh/config or use "ssh -A"
# - remote machine be in local .ssh/authorized_keys
#
#
{% endif %}

{% if yadm.class == "personal_mac" %}
# Use the 1Password SSH agent. Keys live in 1Password (not on disk), so there
# is no local ssh-agent to start and no key files to ssh-add.
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
{% endif %}
