formats = ["ipynb", "py:percent"]
notebook_metadata_filter = "all,-kernelspec,-jupytext.cell_metadata_filter,-jupytext.notebook_metadata_filter,-jupytext.text_representation.format_version,-jupytext.text_representation.jupytext_version"
cell_metadata_filter = "tags,-all"
