## Get symbols from: https://www.nerdfonts.com/cheat-sheet

[gcloud]
# For some reason there's a spurious block space character in the default
symbol = " "

[python]
symbol = " "

[package]
symbol = " "

[docker_context]
symbol = " "

[hostname]
ssh_symbol = " "
style = "bold inverted bright-green"

[conda]
ignore_base = false

