[gcloud]
# For some reason there's a spurious block space character in the default
symbol = " "

[python]
symbol = " "

[package]
symbol = " "

[docker_context]
symbol = " "

[hostname]
style = "bold inverted bright-green"
