## Get symbols from: https://www.nerdfonts.com/cheat-sheet

[gcloud]
# For some reason there's a spurious block space character in the default
symbol = " "
disabled = true

[python]
# symbol = " "
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

[package]
disabled = true

[docker_context]
symbol = " "

[hostname]
style = "bold inverted bright-green"
format = '[$ssh_symbol$hostname]($style) '

[conda]
ignore_base = false
format = '[$symbol$environment]($style) '

[aws]
symbol = " "
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style)'

[aws.profile_aliases]
AdministratorAccess-818347758896 = 'instant'

[aws.region_aliases]
ca-central-1 = 'ca1'

[username]
format = '[$user]($style)'

[git_status]
diverged = "\uebdb"
conflicted = "\ue654"
modified = "\uea73"
staged = "\uf440"
format = '([\[$conflicted$modified$staged$ahead_behind\]]($style) )'

[custom.dvc_dirty]
detect_files = ["dvc.lock"]
# check icon: https://www.nerdfonts.com/cheat-sheet
command = ''' just dvc_is_synced || echo "DVC \ueb43" '''
style = "bold red"
format = '[ $output ]($style) '
