[settings]
experimental = true
verbose = false
idiomatic_version_file_enable_tools = []

trusted_config_paths = [
    '~/dev/plus',
]



status.show_env = true

[tools]
atuin = "latest"
bun = "latest"
codex = "latest"
delta = "latest"
difftastic = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
"github:agavra/tuicr" = "latest"
gum = "latest"
jless = "latest"
jq = "latest"
lsd = "latest"
node = "22.21.1"
ripgrep = "latest"
starship = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
